language: python
python:
  - "2.7"
services:
  - mysql
addons:
  apt:
    packages:
      - python-dev
      - build-essential
      - libatlas-base-dev
      - gfortran
      - python-numpy
      - python-scipy
before_install:
  - git clone --recursive https://github.com/noporpoise/seq-align ~/seq-align
  - cd ~/seq-align && make
install:
  - python setup.py install
before_script:
  - mysql -u root -e 'SET GLOBAL innodb_file_format=barracuda;';
  - mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;';
  - mysql -u root -e 'SET GLOBAL innodb_large_prefix=ON;';
script:
  - LL_PATH=~/seq-align/bin/needleman_wunsch ./tests/run.sh
