language: python
python:
  - "2.7"
cache: pip
services:
  - mysql
addons:
  apt:
    packages:
      - python-dev
      - build-essential
      - libatlas-base-dev
      - gfortran
virtualenv:
  system_site_packages: true
install:
  - pip install numpy
  - python setup.py install
  - pip install nose
  - git clone --recursive https://github.com/noporpoise/seq-align ~/seq-align
  - cd ~/seq-align && make
before_script:
  - mysql -u root -e 'SET GLOBAL innodb_file_format=barracuda;';
  - mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;';
  - mysql -u root -e 'SET GLOBAL innodb_large_prefix=ON;';
script:
  - cd $TRAVIS_BUILD_DIR
  - LL_PATH=~/seq-align/bin/needleman_wunsch ./tests/run.sh

