language: python
python:
  - "2.7"
services:
  - mysql
before_install:
  - apt-get install -y python-pip python-dev build-essential
  - apt-get install -y libatlas-base-dev gfortran
  - apt-get install -y python-numpy
  - apt-get install -y python-scipy
  - git clone --recursive https://github.com/noporpoise/seq-align ~/seq-align
  - cd ~/seq-align && make
install:
  - python setup.py install
before_script:
  - mysql -u root -e 'SET GLOBAL innodb_file_format=barracuda;';
  - mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;';
  - mysql -u root -e 'SET GLOBAL innodb_large_prefix=ON;';
script:
  - LL_PATH=~/seq-align/bin/needleman_wunsch ./tests/run.sh
