language: python
python:
  - "2.7"
virtualenv:
system_site_packages: true
services:
  - mysql
install:
  - sudo apt-get install python-pip python-dev build-essential
  - pip install --upgrade numpy
  - sudo apt-get install libatlas-base-dev gfortran
  - pip install scipy
  - git clone --recursive https://github.com/noporpoise/seq-align ~/seq-align
  - cd ~/seq-align && make
before_install:
  - apt-get install -qq python-numpy python-scipy
before_script:
  - mysql -u root -e 'SET GLOBAL innodb_file_format=barracuda;';
  - mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;';
  - mysql -u root -e 'SET GLOBAL innodb_large_prefix=ON;';
script:
  - LL_PATH=~/seq-align/bin/needleman_wunsch ./tests/run.sh
