version: '2'
services:
  sldb:
    image: arosenfeld/sldb
    ports:
      - 5000:${API_PORT}
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
        - ./docker/mariadb:/etc/mysql/conf.d
        - ${DB_VOLUME}:/var/lib/mysql
        - ${DATA_VOLUME}:/data
    environment:
      - MYSQL_ROOT_PASSWORD=insecure_password
  frontend:
      image: arosenfeld/sldb-frontend
      environment:
        - BASE_URL=${BASE_URL}
        - API_ENDPOINT=${API_ENDPOINT}
        - PRODUCTION=${PRODUCTION}
      ports:
        - 8080:${SERVE_PORT}
