version: '2'
services:
  airrdb:
    image: arosenfeld/airrdb
    volumes:
      - ${DATA_VOLUME}:/root/data:ro
    ports:
      - ${API_PORT}:5000
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
        - ./docker/mariadb:/etc/mysql/conf.d
        - ${DB_VOLUME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=insecure_password
  frontend:
      image: arosenfeld/airrdb-frontend
      environment:
        - BASE_URL=${BASE_URL}
        - API_ENDPOINT=${API_ENDPOINT}
        - PRODUCTION=${PRODUCTION}
      ports:
          - ${SERVE_PORT}:8080
