version: '2'
services:
  sldb:
    image: arosenfeld/sldb
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
        - ./docker/mariadb:/etc/mysql/conf.d
        - ~/.sldb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=insecure_password
  frontend:
      image: arosenfeld/sldb-frontend
      environment:
        - BASE_URL=${BASE_URL}
      ports:
        - "8080:8080"
